// <auto-generated />
namespace ASP_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test27872 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test27872));
        
        string IMigrationMetadata.Id
        {
            get { return "201605261413071_test27872"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
